stages:
  - build
  #- test
  - deploy

variables:
   NODE_ENV: build
   APP_DIR: "E:\\node-pub5"  # Change this to your app's path 1

variables:
  NODE_ENV: production
  APP_DIR: "E:\\node-pub5"  # Change this to your app's path 1

# variables:
#   NODE_ENV: "test"
#   APP_DIR: "E:\\node-pub4"  # Replace with your application path

# before_script:
#   - npm install -g pm2

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install
  only:
    - main  # Runs only on the main branch
  tags:
    - "production"
  # artifacts:
  #   paths:
  #     - node/

# Job to install dependencies and run tests
# test:
#   stage: test
#   script:
#     - echo "Running tests..."
#     - npm install
#     #- npm test
#   only:
#     - main  # Runs only on the main branch
#   tags:
#     - "production"
#Job to deploy the application
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - if (Test-Path $APP_DIR) { Remove-Item -Recurse -Force $APP_DIR }
    - New-Item -ItemType Directory -Path $APP_DIR
    - Copy-Item -Recurse -Path .\* -Destination $APP_DIR
    - cd $APP_DIR
    - npm install
    - npm run build
    #- npm install pm2@latest -g
    #- pm2 start dist/index.js --name node
  only:
    - main  ##  Runs only on the main branch
  tags:
    - "production"